language: python

python:
  - '3.6'

matrix:
  include:
  - python: '3.7'
    dist: xenial

before_install:
  - pip install poetry

install:
  - poetry install -v
  - pip install tox-travis

script:
  - tox

after_success:
  - coverage report
  - coveralls